.EXPORT_ALL_VARIABLES:

CONFIG_FILE ?= CONFIG.cfg

# sets DOCKER, KUBE_CORES, LOCUST_SHAPE, SCHEME
include .env 

# sets LOADGEN_REPLICAS, OB_CORES, OB_REPLICAS, and optionally SCHEME.
include $(CONFIG_FILE)

TOP := .

RELEASE := $(TOP)/release
SRC := $(TOP)/src
BENCH := $(TOP)/benchmark

BASE := $(RELEASE)/base
GENERATED := $(RELEASE)/generated

IMGS := $(BENCH)/imgs
STATS := $(BENCH)/stats

KUBE_BASE_YAML := $(BASE)/kube.yaml
LOAD_BASE_YAML := $(BASE)/loadgen.yaml

# the file passed to `weaver kube deploy`
KUBE_GEN_YAML := $(GENERATED)/kube.yaml

# the file generated by `weaver kube deploy`, passed to `kubectl apply -f`
WEAVER_GEN_YAML := $(GENERATED)/gen.yaml
# also passed to `kubectl apply -f`
LOAD_GEN_YAML := $(GENERATED)/loadgen.yaml

SCHEME_DIR := $(BASE)/colocation
COLOCATION_FNAMES := $(wildcard $(SCHEME_DIR)/*.yaml)
COLOCATION_BASE := $(foreach var, $(COLOCATION_FNAMES), $(shell basename $(var) .yaml))


BIN := $(GENERATED)/ob

LOAD_SRC := $(SRC)/loadgenerator
LOAD_SRC_PY := $(LOAD_SRC)/locustfile.py $(wildcard $(LOAD_SRC)/load_shapes/*.py)
LOAD_SRC_ALL := $(LOAD_SRC_PY) $(LOAD_SRC)/entrypoint.sh  $(LOAD_SRC)/Dockerfile

# All .go files in src/** that aren't generated
MAIN_SRC := $(SRC)/main.go $(filter-out %weaver_gen.go, $(wildcard $(SRC)/*/*.go))

VERSION_FILE := $(GENERATED)/version.txt

LOGS_FILE := $(TOP)/logs.txt
TMP_LOGS := $(TOP)/tmp_logs.txt

ifeq ($(VERBOSE), 1)
	DEBUG_OUTPUT := $(LOGS_FILE)
else
	DEBUG_OUTPUT := /dev/null
endif

.PHONY: all clean minikube_start minikube_restart check_smt toggle_smt deploy bench bench_all stop clear_logs check_docker check_loadgen pre_deploy bench_once

all:
	@echo valid arguments:
	@echo
	@echo "minikube_[re]start   - [re]start minikube"
	@echo "check_smt            - View if hyperthreading is enabled"
	@echo "toggle_smt           - Toggle hyperthreading. NOTE: May require root."
	@echo "deploy               - Starts minikube / builds new version of app if necessary, then deploys."
	@echo "pre_deploy           - Builds new version of app, but does not deploy anything."
	@echo "bench                - Deploys app, and runs script to collect metrics and terminate when load test is complete."
	@echo "bench_all            - Run benchmark using every colocation scheme in release/base/colocation"
	@echo "stop                 - remove deployments"


check_docker: 
	@./make_scripts/check_docker.sh

check_loadgen: $(LOAD_SRC_PY)
	@python3 -m py_compile $(LOAD_SRC_PY)


minikube_start:
	@ lines=$(shell minikube status | wc -l);\
	if [ $$lines -le 5 ]; then\
		echo Starting minikube;\
		./scripts/minikube_start.sh;\
	else\
		echo Minikube already running. ;\
	fi 

# Will try to ignore errors i.e. if minikube wasn't running
minikube_restart:
	- minikube delete
	./scripts/minikube_start.sh

check_smt:
	./scripts/hyperthreading.sh

toggle_smt:
	./scripts/hyperthreading.sh 2


# Update the release/generated/*.yaml files based on config env vars.
# Check to make sure all the prerequisites for deploy execute properly. 
# Does not actually deploy anything.
# check_docker should prevent gen yaml scripts from firing without `$$DOCKER` being set.
pre_deploy: check_docker check_loadgen $(WEAVER_GEN_YAML) $(LOAD_GEN_YAML)
	@./make_scripts/check_env.sh
	@echo 																								| tee -a $(LOGS_FILE)
	@echo "scheme:                    $$SCHEME"						| tee -a $(LOGS_FILE)
	@echo "loadshape:                 $$LOCUST_SHAPE"			| tee -a $(LOGS_FILE)
	@echo "loadgenerator workers:     $$LOADGEN_REPLICAS"	| tee -a $(LOGS_FILE)
	@echo "cores per OB pod:          $$OB_CORES"					| tee -a $(LOGS_FILE)
	@echo "replicas per fusion group: $$OB_REPLICAS" 			| tee -a $(LOGS_FILE)
	@echo 																								| tee -a $(LOGS_FILE)
	
	@echo pre deploy check / code gen complete.

# release/generated/gen.yaml and release/generated/loadgen.yaml
deploy: minikube_start pre_deploy
	@echo deploying onlineboutique, loadgenerator...| tee -a $(LOGS_FILE)
	
	@# Remove any old deployment.
	@-kubectl delete all --all >>$(DEBUG_OUTPUT) 2>&1

	@# should be first so that if running on a NUMA architecture, first socket can be entirely used.
	@kubectl apply -f $(LOAD_GEN_YAML) >> $(DEBUG_OUTPUT) 2>&1
	@kubectl apply -f $(WEAVER_GEN_YAML) >> $(DEBUG_OUTPUT) 2>&1


# Can be run by user 
# Used to benchmark app under environment specified by env vars
bench: deploy	
	./scripts/pull_stats.sh 
	@echo deleting deployment...
	@-kubectl delete all --all >> $(DEBUG_OUTPUT) 2>&1
	@./make_scripts/post_bench.sh

# Shouldn't be ran by user, used by bench_all.
bench_once: deploy
	./scripts/pull_stats.sh

# ./bench_all changes $(WEAVER_GEN_YAML) every time it runs, 
# 	new images built each time.
bench_all: minikube_start clear_logs
	@echo Colocation Schemes: $(COLOCATION_BASE)
	@echo 
	./make_scripts/bench_all.sh

stop:
	./scripts/stop.sh
	minikube delete

# if deployment specifications or src code was modified,
# 	Update Weaver kubernetes yaml
# 	modifies version file, which should trigger LOAD_GEN_YAML
$(WEAVER_GEN_YAML): $(KUBE_BASE_YAML) $(KUBE_GEN_YAML) $(BIN) $(CONFIG_FILE) .env
	@echo rebuilding onlineboutique container...
	@./make_scripts/weaver_gen_yaml.sh 

# if deployment specifications or loadgen code was modified, 
#	Update Load Generator
$(LOAD_GEN_YAML): $(LOAD_SRC_ALL) $(VERSION_FILE) $(LOAD_BASE_YAML) $(CONFIG_FILE) .env
	@echo rebuilding loadgenerator container...
	@./make_scripts/load_gen_yaml.sh

# If src code was modified, 
#	Update binary
$(BIN): $(MAIN_SRC)
	@echo rebuilding binary...

	@cd $(SRC); weaver generate ./...; go build -o ../release/generated; cd ..
	@mv release/generated/onlineboutique release/generated/ob

clear_logs: $(LOGS_FILE)
	@echo clearing logs...
	@printf "" > $(LOGS_FILE)

$(LOGS_FILE):
	@echo creating $(LOGS_FILE)...
	@touch $(LOGS_FILE)
