TOP ?= .

RELEASE := $(TOP)/release
SRC := $(TOP)/src
BENCH := $(TOP)/benchmark
BASE := $(RELEASE)/base
GENERATED := $(RELEASE)/generated
TELEMETRY := $(RELEASE)/telemetry

STATS := $(BENCH)/stats

KUBE_BASE_YAML := $(BASE)/kube.yaml
LOAD_BASE_YAML := $(BASE)/loadgen.yaml

# the file passed to `weaver kube deploy`
KUBE_GEN_YAML := $(GENERATED)/kube.yaml

# the file generated by `weaver kube deploy`, passed to `kubectl apply -f`
WEAVER_GEN_YAML := $(GENERATED)/gen.yaml
# also passed to `kubectl apply -f`
LOAD_GEN_YAML := $(GENERATED)/loadgen.yaml

#The files passed to `kubectl apply -f`, export telemetry
JAEGER_TRACE_YAML := $(TELEMETRY)/jaeger.yaml
PROMETHEUS_METRIC_YAML := $(TELEMETRY)/prometheus.yaml

SCHEME_DIR := $(BASE)/colocation

RESOURCE_SPEC_FILE := $(BASE)/resourceSpec.yaml
SCALING_SPEC_FILE := $(BASE)/scalingSpec.yaml
SCALING_DEFS_FILE := $(SCHEME_DIR)/scalingdefs.cfg
GROUPS_FILE := $(GENERATED)/groups.yaml

BIN := $(GENERATED)/ob

LOAD_SRC := $(SRC)/loadgenerator
LOAD_SRC_PY := $(LOAD_SRC)/locustfile.py $(wildcard $(LOAD_SRC)/load_shapes/*.py)
LOAD_SRC_ALL := $(LOAD_SRC_PY) $(LOAD_SRC)/entrypoint.sh  $(LOAD_SRC)/Dockerfile

# All .go files in src/** that aren't generated
MAIN_SRC := $(SRC)/main.go $(filter-out %weaver_gen.go, $(wildcard $(SRC)/*/*.go))

VERSION_FILE := $(GENERATED)/version.txt

LOGS_FILE := $(TOP)/logs.txt
TMP_LOGS := $(TOP)/tmp_logs.txt

WEAVER_BIN_PATH := $(shell dirname $(shell which weaver-kube))
