apiVersion: v1
kind: Service
metadata:
  labels:
    app: memcached
  name: memcached
spec:
  ports:
  - port: 11211
    name: memcached
  - port: 9150
    name: prometheus

  selector:
    app: memcached
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memcached
  labels:
    app: memcached
spec:
  selector:
    matchLabels:
      app: memcached
  replicas: 1
  template:
    metadata:
      labels:
        app: memcached
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      # securityContext: 
      #   fsGroup: 1000
      #   runAsGroup: 1000
      #   runAsNonRoot: true
      #   runAsUser: 1000
      
      containers:
      - name: memcached
        image: memcached
        # env:
        # - name: MEMCACHED_PROMETHEUS_ENABLED
        #   value: "false" # Can change later
        ports:
        - containerPort: 11211
          name: memcached
        resources:
          requests:
            cpu: 1
            memory: "250Mi"
          limits:
            cpu: 1
            memory: "250Mi"
        # readinessProbe:
        #   initialDelaySeconds: 10
        #   periodSeconds: 30
        #   timeoutSeconds: 20
        #   failureThreshold: 6
        #   successThreshold: 1