# CURRENTLY UNUSED

apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-redis
  name: product-redis
spec:
  ports:
  - port: 6379
    name: redis
  
  selector:
    app: product-redis
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-redis
  labels:
    app: product-redis
spec:
  selector:
    matchLabels:
      app: product-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: product-redis
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext: 
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
  
      containers:
      - name: product-redis
        image: redis:alpine
        command:
        - redis-server
        - "/redis-config/redis.conf"
        ports:
        - containerPort: 6379
          name: redis
          
        volumeMounts:
        - name: redis-data
          mountPath: /data        
        - name: redis-config
          mountPath: /redis-config

        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: "1"
            memory: 1Gi
        
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 5
        
      volumes:
      - name: redis-data
        emptyDir: 
          sizeLimit: 15Gi
      - name: redis-config
        configMap:
          name: product-redis-config
          items:
          - key: redis-config
            path: redis.conf


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: product-redis-config
  labels:
    app: product-redis
data:
  redis-config: |
    maxmemory 500mb
    maxmemory-policy allkeys-lru
