apiVersion: v1
kind: Service
metadata:
  labels: 
    app: loadgenerator
  name: loadgenerator
spec:
  ports:
  - port: 5557
    name: comm
  - port: 8089
    name: web-ui
  - port: 5558
    name: comm-plus-one
  selector:
    app: loadgenerator
  type: ClusterIP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  labels:
    app: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  replicas: 1
  template:
    metadata:
      labels:
        app: loadgenerator
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

      containers:
      - name: loadgenerator
        volumeMounts:
        - name: load-logs
          mountPath: /stats

        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: false
        image: <DOCKER>/loadgen:<VERSION>
        imagePullPolicy: IfNotPresent
        env:
        - name: LOCUST_MODE
          value: MASTER

        - name: FRONTEND_ADDR
          value: <ADDR>
        
        - name: LOADGEN_REPLICAS
          value: <LOADGEN_REPLICAS_ENV>

        - name: LOCUST_SHAPE
          value: <LOCUST_SHAPE>

        resources:
          requests:
            cpu: 1
            memory: 512Mi
          limits:
            cpu: 1
            memory: 512Mi

        ports:
        - containerPort: 5557
          name: comm
        - containerPort: 5558
          name: comm-plus-one
        - containerPort: 8089
          name: web-ui
      volumes:
      - name: load-logs
        emptyDir:
          sizeLimit: 300Mi


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: loadgenerator-worker
  name: loadgenerator-worker
spec:
  replicas: <LOADGEN_REPLICAS>
  selector:
    matchLabels:
      app: loadgenerator-worker
  template:
    metadata:
      labels:
        app: loadgenerator-worker
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000

      containers:
      - name: loadgenerator-worker
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true


        image: <DOCKER>/loadgen:<VERSION>
        imagePullPolicy: IfNotPresent
        env:
        - name: LOCUST_MODE
          value: WORKER

        - name: LOCUST_MASTER
          value: loadgenerator
        
        - name: FRONTEND_ADDR
          value: "<ADDR>"

        resources:
          requests: 
            cpu: "1"
            memory: "1024Mi"
          limits:
            cpu: "1"
            memory: "1024Mi"

