#!/bin/bash

cd $(dirname $0)/../cfgs

name=$1

cat << EOF > $name.cfg
SCHEME=$1
C_SCHEME=groups_height
LOADGEN_REPLICAS=31
OB_CORES=1
OB_REPLICAS=50
FIXED=main
FIXED_HEIGHT=2
FIXED_WIDTH=1
ALLOC_FILE=*
CRITICAL_SCALE_UTIL=75
NONCRITICAL_SCALE_UTIL=75
TRIVIAL_SCALE_UTIL=75
FALLBACK_SCALE_UTIL=65
CRITICAL_MIN_REPLICAS=1
NONCRITICAL_MIN_REPLICAS=1
TRIVIAL_MIN_REPLICAS=1
FALLBACK_MIN_REPLICAS=1
EOF
