[serviceweaver]
binary = "./onlineboutique"
rollout = "5m"

colocate = [
  [
    "github.com/ServiceWeaver/weaver/Main",
    "github.com/ServiceWeaver/onlineboutique/adservice/AdService"
  ],
  [
    "github.com/ServiceWeaver/onlineboutique/checkoutservice/CheckoutService",
    "github.com/ServiceWeaver/onlineboutique/emailservice/EmailService",
    "github.com/ServiceWeaver/onlineboutique/paymentservice/PaymentService"
  ],
  [
    "github.com/ServiceWeaver/onlineboutique/cartservice/CartService",
    "github.com/ServiceWeaver/onlineboutique/cartservice/cartCache"
  ]
]

[single]
listeners.boutique = {address = "localhost:12345"}

[multi]
listeners.boutique = {address = "localhost:12345"}
replicas = [
  {group = "github.com/ServiceWeaver/weaver/Main", cpus="1"},
  {group = "github.com/ServiceWeaver/weaver/Main", cpus="2"},
  {group = "github.com/ServiceWeaver/weaver/Main", cpus="3"},
  {group = "github.com/ServiceWeaver/onlineboutique/adservice/AdService", cpus="4-7"}
]
